name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  NEXT_PUBLIC_CMS_URL: ${{ secrets.NEXT_PUBLIC_CMS_URL }}
  CMS_API_URL: ${{ secrets.CMS_API_URL }}
  CMS_API_TOKEN: ${{ secrets.CMS_API_TOKEN }}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint, ʦ TypeScript, 💅 Prettier, and 🃏 Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: 🤌 Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: 📥 Download deps
        run: pnpm install --frozen-lockfile

      - name: 🔬 Lint
        run: pnpm run lint:strict

      - name: 🔎 Type check
        run: pnpm run typecheck

      - name: 💅 Prettier check
        run: pnpm run format:check

      - name: 🃏 Run jest
        run: pnpm run test:coverage

      - name: 📊 Upload coverage
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: 📦 Build
        run: pnpm run build

      - name: 🌐 Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: 🐳 Run Playwright tests
        run: pnpm run test:e2e
